In [1]:
import numpy as np
import pandas as pd
from numpy import random as rnd
import math
import copy
import bisect
from collections import Counter, deque, namedtuple, defaultdict
import functools
import random
import operator
import itertools


In [17]:
N = float(input("введите сумму в рублях"))
G_R = float(input("введите price grechki в рублях"))
G_K = float(input("введите price grechki в рублях"))
G_P = G_R + G_K/100

M_R = float(input("введите price icecr в рублях"))
M_K = float(input("введите price icecr в рублях"))
M_P = M_R + M_K/100

        

введите сумму в рублях345
введите price grechki в рублях33
введите price grechki в рублях22
введите price icecr в рублях12
введите price icecr в рублях12


In [14]:
N = 73.72
G_R = 36
G_K = 36
G_P = G_R + G_K/100

M_R = 12
M_K = 12
M_P = M_R + M_K/100

In [18]:
n_pak = N // G_P
print(n_pak)
if N % G_P > M_P:
    print('Yes')
else:
    print('No')

10.0
Yes


In [61]:
#m = []
#nenuzhnaia_dlina = int(input(('vveditr dlinu'))
#for i in range(nenuzhnaia_dlina):
#    m.append(int(input('vvedi otsenku: ')))

m = [2,5,4,5,3,4,5,2,2,3,4,5,2,2,2,4,5,5,4,4,4,4,4,3,4,4,2,5,5,5,5,5,5,5,5,5,5,5,5]
flag_do_we_have_seq = False

max_len_global = 0
max_len_local = 0
n_seq = 0

set_good = {4,5}
set_bad = {1,2,3}
for i in m:
    if i in set_good:
        flag_do_we_have_seq = True
        max_len_local += 1
    elif i in set_bad:
        if flag_do_we_have_seq: # end of good seq
            max_len_global = max(max_len_global, max_len_local)
            max_len_local = 0
            n_seq += 1
            flag_do_we_have_seq = False
            #print(f'test i/n {i}, {n_seq}')
        else: # still bad seq
            pass
    else:
        print(f'ne byvaet takoi otsenki {i}')
    
if m[-1] in set_good:
    n_seq += 1
    max_len_global = max(max_len_global, max_len_local)

    
print(f'n seq {n_seq}')
print(f'max_len {max_len_global}')


n seq 6
max_len 12


In [62]:
m = [2,5,4,5,3,4,5,2,2,3,4,5,2,2,2,4,5,5,4,4,4,4,4,3,4,4,4,4,4,4,2,5,5,5,5,5,5,5,5,5,5,5,5]
set(m)

{2, 3, 4, 5}

In [40]:
note  = 'qwe rtyu Iiiii, iiiii, qwe'
b = [word for word in note.split()]
c = Counter(b)
del c['qwe']
c

Counter({'rtyu': 1, 'Iiiii,': 1, 'iiiii,': 1})

In [22]:
class Testclass():
    def __init__(self, n):
        self.n = n
    
    def __eq__(self, other):
        return(2 * self.n == other.n)
    
    def __repr__(self):
        return(f'ЭТО вот что: {self.n}. И для отстающих повторяю - ВОТ ЧТО: {self.n}')
    
    def __hash__(self):
        return(self.n**2 % 11)
        
if __name__ == '__main__':
    a = Testclass(5)
    b = Testclass(5)
    c = Testclass(10)
    
    print("a == b ?", a==b)
    print("a == c ?", a==c)


a == b ? False
a == c ? True


In [23]:
d = Testclass(77)
print(d)
hash(b)

s = 

ЭТО вот что: 77. И для отстающих повторяю - ВОТ ЧТО: 77


3

In [83]:
results = []
def pnc(n):
    deliteli = []
    for d in range(1,(n+1)):
        if n % d == 0:
            deliteli.append(d)
            
    return(deliteli)

pnc(800)

[1, 2, 4, 5, 8, 10, 16, 20, 25, 32, 40, 50, 80, 100, 160, 200, 400, 800]

In [103]:
dict(i for i in range(4))
#np.product([1,2,3,4, 5])

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [ ]:
# find a chain of unique 2 digits numbers divisable by 7 or 13 (for Pasha)

def find_next(digit, list_to_search): #fine tuned
    result = []
    for i in list_to_search:
        x = digit * 10 + int(i)
        if x % 13 == 0 or x % 7 == 0:
            result.append(i)       
            
    return(result)
             
a_master = [i for i in range(1, 10)]

for start in a_master:
    a_copy = copy.copy(a_master)
    path = []
    graph = {}
    a_copy.remove(start)
    path.append(start)
    
    while a_copy and path:
        if not path[-1] in graph.keys():
            list_of_next_vert = find_next(path[-1], a_copy)
            graph[path[-1]] = list_of_next_vert
        #print(f'current path {path}, next verteces are {graph[path[-1]]}')
        #print(f'graph.keys {graph.keys()},   still available {a_copy} \n')
        
        if len(graph[path[-1]]) == 0: 
            wrong_step = path.pop()
            a_copy.append(wrong_step)
            del graph[wrong_step]
            flag = False 
        else:
            next_step = graph[path[-1]].pop()
            path.append(next_step)
            a_copy.remove(next_step)  
            flag = True 
            
    if not flag:
        print(f'no results for path starting from {start}')
    else:
        break

if flag:
    print(f"we found {path}")
else:
    print(f"we DID NOT found it")

    

In [ ]:
from typing import Dict
memo: Dict[int, int] = {0: 0, 1: 1} # our base cases
def fib3(n: int) -> int: 
    if n not in memo:
        memo[n] = fib3(n - 1) + fib3(n - 2) # memoization return memo[n]
    return(memo[n])

In [ ]:
from typing import Dict
memo: Dict[int, int] = {0: 0, 1: 1} # our base cases
def fib3(n: int) -> int: 
    if n not in memo:
        memo[n] = fib3(n - 1) + fib3(n - 2) # memoization return memo[n]
    return(memo[n])

In [ ]:
math.prod([3141592653589793238462643383279502884197169399375105820974944592,2718281828459045235360287471352662497757247093699959574966967627])

In [ ]:
a = '11111'
b = len(a)//2
#kar_prod("11223","222222")
str(10*int(a[:b]))

In [ ]:
def divide(x,y):
    y_power, power, result = (y<<32), 32, 0
    while x >= y:
        while y_power > x:
            y_power >>= 1
            power -= 1
        x -= y_power
        result += (1<<power)
    return result, x

divide(21,4)

In [ ]:
def power_book(x,y):
    power, result = y, 1
    while power:
        if power & 1: 
            result = result * x
        x = x * x
        power >>= 1
    return result

power_book(3,4)     

In [ ]:
a = 27
b = -1
c = a^b
print(f'{a:05b}\n{b:05b}\n{c:05b} XOR\n', a, -a-1)

In [ ]:
import collections
Rectangle = collections.namedtuple('Rectangle', ('x', 'y', 'width', 'height'))

In [ ]:
import copy
import bisect  
a = {1:[1,2,3,5,6], 2:[4,5,6]}
b = copy.deepcopy(a)
print(bisect.insort_left(a[1], 1))

print('a is', a, 'b is', b)

In [ ]:
def multiply(num1, num2):
    sign = -1 if (num1[0] < 0) ^ (num2[0] < 0) else 1 
    num1[0] , num2[0] = abs(num1[0]) , abs(num2[0])
    result = [0] * (len(num1) + len(num2)) 
    for i in reversed(range(len(num1))):
        for j in reversed(range(len(num2))) :
            result[i + j + 1] += num1[i] * num2[j] 
            result[i + j] += result[i + j + 1] // 10 
            result[i+j+1] %= 10
    # Renove the Teading zeroes,
    print('result with leading zeros', result)
    result = result[next((i for i, x in enumerate(result)
                            if x != 0), len(result)):] or [0] 
    return [sign * result[0]] + result[1:]

In [ ]:
print(multiply([1,2,3,4], [5,6,7,8]), 1234*5678)
result = multiply([1,2,3,4], [5,6,7,8])
result+=[0,0,0]
result.reverse()
result

In [ ]:
a = next((i for i, x in enumerate(result) if x != 0), 1)
#type(i for i, x in enumerate(result) if x != 0)
#result[1,4:]
print(a)

In [ ]:
for a in ((i for i, x in enumerate(result) if x != 0)):
    print(a)

In [ ]:
result = [0]
for a in range(10):
    for b in range(10):
        for c in range(10):
            z = 100*a + 10*b + c - 100*c - 10*b - a
            zz = z*z
            if zz%1 == 0:
                result.append(100*a+10*b+c)

print("we found nothing", result)

In [ ]:
n = 101

prost = False
for x in range (2,n):
    if n%x == 0: prost = True
        
print(n, prost)

In [ ]:
a = 43.35 - 0.28
x = 2
print(f'asd {a:1.5f}')
print(f'{x:2.4f} {x*x:3.5f} {x*x*x:4.6f}')
a

In [ ]:
# 5.5 remove duplicates from the sorted array
a = [1,3,4,4,4,5,6,6,6,7,7,8,9]
w_i = 1
for i in range(1, len(a)):
    if a[i] != a[w_i - 1]:
        a[w_i] = a[i]
        w_i += 1
a[:w_i]

In [ ]:
# 5.9 prime generator
def list_of_primes(n):
    is_prime = [False, False] + [True]*(n-1)
    prime = []
    for i in range(2, n+1):
        if is_prime[i]:
            prime.append(i)
            for k in range(i , n + 1, i):
                is_prime[k] = False
    return(prime)

list_of_primes(21)

In [ ]:
#5.16 Generate nonunifirm random number
def nonunif_rnd(n, p):
    p_acc = []
    p_acc.append(p[0])
    for i, x in enumerate(p[1:]): 
        p_acc.append(p_acc[i] + x)
    i = bisect.bisect(p_acc, rnd.rand())
    
    return n[i]

n = [1,2,3,4,5]
p = [.025, .1, .125, .25, .50]
N =10000

a = [nonunif_rnd(n,p) for x in range(N)]
a.sort()
b = list(Counter(a).keys())
c = list(Counter(a).values())
[i/N  for i in c]

In [ ]:
# 5.17 filter/map/ any function
a = list(rnd.randint(1,100,10))
b = list(filter(lambda x: x>50, a))
c = list(map(lambda x: x*x, b))

print(f'before filtering {a}\nafter filtering {b} \nafter b**2 map {c}')
any(i>100 for i in a)


In [ ]:
# 5.20 pascal triangle
def pas_tri(n):
    pt = [[1]*(i+1) for i in range(n)]
    for i in range(n):
        for j in range(1,i):
            #print(f'i={i} j={j} pt[{i-1}][{j-1}]={pt[i-1][j-1]} pt[{i-1}][{j}]={pt[i-1][j]} \n')
            #print(f'i={i} j={j} pt[{i-1}][{j-1}] + pt[{i-1}][{j}] {pt[i-1][j-1] + pt[i-1][j]} \n')
            #pt[i][j] = pt[i-1][j-1] + pt[i-1][j]
            pt[i][j] = pt[i-1][j-1] + pt[i-1][j]

    return(pt)
    
print(pas_tri(5))

In [ ]:
#6.1 int to string

def int_to_string(x):
    is_negat = False
    if x < -0:
        x, is_negat = -x, True
    s = []
    while True:
        s.append(chr(ord('0') + x % 10))
        x //= 10
        if x == 0: break
    return ('-'if is_negat else '') + ''.join(reversed(s))

int_to_string(234)

In [ ]:
#6.2 base conversion
import string
def conv(n_as_string, b1, b2):
    def construct_from_base(n_as_int, base):
        return ('' if n_as_int == 0 else 
                construct_from_base(n_as_int // base, base) + 
                string.hexdigits[n_as_int % base].upper())
    n = 0
    for i in n_as_string:
        n = n * b1 + string.hexdigits.index(i)
    
    return ('0' if n == 0 else construct_from_base(n, b2))

conv('1111', 2, 16)

In [ ]:
# 6.3 spreadsheet column encoding

def ss_decode(col):
    return functools.reduce(
        lambda result, c: result * 26 + ord(c) - ord('A') + 1, col, 0)
    
print(ss_decode("A"))
    

In [ ]:
#7.1 linked lists. merge two sorted

class ListNode:
    def __init__(self, data=0, next_node = None):
        self.data = data
        self.next_node = next_node
    
class LinkedList:
    def __init__(self):
        self.headval = None
    
    def insert_after(self, node, new_node):
        new_node.next = node.next
        node.next = new_node

    def delete(self, node):
        node.next = node.next.next
        
    def print_LL(self):
        a = self.headval
        while a.next_node != None:
            print(a.data)
            a = a.next_node
        print(a.data)


LL = LinkedList()
LL.headval = ListNode("Mon")
LN1 = ListNode("Tue")
LN2 = ListNode("Wed")
LN3 = ListNode("Thu")
a =3
LL.headval.next_node = LN1
LN1.next_node = copy.copy(LN2)
LN2.next_node = LN3

LN2.data = "Wedddd"

a = LL.headval.next_node
a.next_node.data

In [ ]:
# 8.2 Reverse Polish Notation

def evaluate_RPN(RPN_input):
    interim_results = []
    delimeter = ','
    
    operator = {"+": lambda y, x: x + y, "-": lambda y, x: x - y}
    
    for token in RPN_input.split(delimeter):
        if token in operator.keys():
            interim_results.append(operator[token](
                interim_results.pop(), interim_results.pop()))
        else:
            interim_results.append(int(token))
        print(interim_results)
    return(interim_results[-1])

evaluate_RPN('3,4,+,5,-, 4,+')
        


In [ ]:
# 8.3 well-formedness check

def check_string(input_string):
    stack = []
    dict_open = {'{': 1, '[': 2, '(': 3}
    dict_close = {'}': -1, ']': -2, ')': -3}
    
    for token in input_string:
        if token in dict_open.keys():
            stack.append(dict_open[token])
            flag = True
        elif dict_close[token] + stack.pop() != 0: 
                flag = False
                break
    
    return(flag)

check_string('(({{[]}}(){}))')


In [ ]:
# 8.5 sunset view building

def sunset_check(heights): # heights from east to west
    sunset_stack = [0]
    for b in heights:
        while sunset_stack and b >= sunset_stack[-1]:
            sunset_stack.pop()
        sunset_stack.append(b)
    return(sunset_stack)

sunset_check([20,15,16, 14,12,9,11])
        

In [ ]:
# 8.9 queue with max API

class QueueeWithMax:
    def __init__(self): 
        self.data = deque()
        self.cand_for_max = deque()
    
    def enq(self, x) -> None:
        self.data.append(x)
        while self.cand_for_max and self.cand_for_max[-1] < x:
            self.cand_for_max.pop()
        self.cand_for_max.append(x)
        
    def deq(self):
        if self.data:
            if self.data[0] == self.cand_for_max[0]:
                self.cand_for_max.popleft()
            return self.data.popleft()
        raise IndexError("empty queue")
    
    def max(self):
        return self.cand_for_max[0]
        
        
if __name__ == "__main__":
    a = QueueeWithMax()
    for _ in range(11): a.enq(rnd.randint(1,100))   
    print(f'{a.data} \n{a.cand_for_max}, max is {a.cand_for_max[0]}')
    for _ in range(3): a.deq()
    print(f'after 3 deq \n{a.data} \n{a.cand_for_max}, max is {a.cand_for_max[0]}')




In [74]:
#9.3is a binary tree simmetric?
class Node:
        def __init__ (self, data, left = None, right = None):
            self.data = data
            self.left = left
            self.right = right
            
        def add_node (self, direction, data, left = None, right = None): #direction 0 - left, 1 - right
            if not direction:
                self.left = Node(data, left, right)
            else:
                self.right = Node(data, left, right)
                
class Bin_Tree:
        
    def __init__(self, data, left, right):
        self.root = Node(data, left, right)
    
    
    def is_symmetric(self):
        
        def check_symmetric(node_left, node_right):
            if not node_left and not node_right:
                return(True)
            elif node_left and node_right:
                result = node_left.data == node_right.data and\
                check_symmetric(node_left.left, node_right.right) and\
                check_symmetric(node_left.right, node_right.left)
            
                return(result)
            return(False)
        
        return check_symmetric(self.root.left, self.root.right)
  
        
if __name__ == "__main__":
    b = Bin_Tree(11, None, None)
    #print(b.is_symmetric())

In [114]:
#9.5 BINARY sum of paths?

class Node:
        def __init__ (self, data, left = None, right = None):
            self.data = data
            self.left = left
            self.right = right
            
        def add_node (self, direction, data, left = None, right = None): 
            '''#direction 0 - left, 1 - right'''
            if not direction:
                self.left = Node(data, left, right)
            else:
                self.right = Node(data, left, right)
                
class Bin_Tree:
        
    def __init__(self, data, left, right):
        self.root = Node(data, left, right)
        self.h = 1
    
    def generate_tree(self, h):
        '''generates a balanced binary tree with depth h'''
        
        def add_two_nodes(node, h_current):
            node.add_node(0, rnd.binomial(1, 0.5))
            node.add_node(1, rnd.binomial(1, 0.5))
            if h_current + 1 == h:
                return
            else:
                h_current += 1
                add_two_nodes(node.left, h_current)
                add_two_nodes(node.right, h_current)
 
        add_two_nodes(self.root, self.h)
        self.h = h  
    
    def sum_root_to_leafs(self):
        '''calculate the sum of all the paths from root to leafs'''
        
        def find_node_sum(node, s_parent):
            '''calculate sum of two paths (from the root to node.left and to node.right)
            for the path from the root to the node sum is equal to s_parent'''
            
            if not node.left and not node.right:
                return s_parent
            elif not node.right: 
                return find_node_sum(node.left, s_parent * 2 + node.left.data)
            elif not node.left:
                return find_node_sum(node.right, s_parent * 2 + node.right.data)
            else:
                return find_node_sum(node.left, s_parent * 2 + node.left.data) +\
                        find_node_sum(node.right, s_parent * 2 + node.right.data)
        
        return(find_node_sum(self.root, self.root.data))

            
        
if __name__ == "__main__":
    a = Bin_Tree(1, None, None)
    a.generate_tree(9)
    print(bin(a.sum_root_to_leafs()))
    print(a.root.data, a.root.left.data)
    print(a.root.data, a.root.right.data)
    #print(b.is_symmetric())

0b11010111101111101
1 1
1 1


In [26]:
a.root.add_node(0, 1)
a.root.add_node(1, 0)
t = a.root.left
t.add_node(0, 1)
t.add_node(1, 0)
t = a.root.right
t.add_node(0, 1)
t.add_node(1, 0)

#print(t.left)
print(a.root.left.right.data)


0


In [241]:
#9.6 does this sum exist? # 9.7 preorder_traversal

class Node:
        def __init__ (self, data, left = None, right = None):
            self.data = data
            self.left = left
            self.right = right
            
        def add_node (self, direction, data, left = None, right = None): 
            '''#direction 0 - left, 1 - right'''
            if not direction:
                self.left = Node(data, left, right)
            else:
                self.right = Node(data, left, right)
                
class Bin_Tree:
        
    def __init__(self, data, left, right):
        self.root = Node(data, left, right)
        self.h = 1
    
    def generate_tree(self, h):
        '''generates a balanced binary tree with depth h'''
        
        def add_two_nodes(node, h_current):
            node.add_node(0, round(random.uniform(0,100)))
            node.add_node(1, round(random.uniform(0,100)))
            if h_current + 1 == h:
                return
            else:
                h_current += 1
                add_two_nodes(node.left, h_current)
                add_two_nodes(node.right, h_current)
 
        add_two_nodes(self.root, self.h)
        self.h = h  
    
    def sum_exist(self, s):
        '''return True if there is a root-leaf path with sum of .data == s'''
        
        def level_down(node, s_parent):
            '''propagete (s_parent - s.data) to two left_down calls (for left and for right)'''
            if not node:
                return(False)
            
            s_children = s_parent - node.data
            if node.left or node.right:
                return(level_down(node.left, s_children) or level_down(node.right, s_children))
            else:
                return(node.data == s_parent)
        
        res = level_down(self.root, s)
        return(res)

    def preorder_traversal(self, root_node):
        path, results = deque([root_node]), []
        while path:
            node = path.popleft()
            if node: 
                results.append(node.data)
                path.append(node.left)
                path.append(node.right)
        print(results)    
        
if __name__ == "__main__":
    a = Bin_Tree(1, None, None)
    a.generate_tree(3)
    a.preorder_traversal(a.root)
    
    print(a.root.data, a.root.left.data, a.root.left.left.data)
    print(a.root.data, a.root.right.data, a.root.right.right.data)
    print(a.sum_exist(49))


    #print(b.is_symmetric())

[1, 88, 6, 0, 21, 95, 34]
1 88 0
1 6 34


In [25]:
#11.10 Finf the missing

class Missing:
    def __init__(self, N):
        self.N = N
        self.numbers = np.arange(N, dtype=int)
        mask = np.ones(N, dtype=bool)
        self.missing = round(np.random.uniform(N))
        mask[self.missing] = False
        self.numbers = self.numbers[mask]
    
    def find_missing(self):
        #xor = functools.reduce(lambda x,y: x^y, range(0,self.N-1))
        xor = functools.reduce(lambda x,y: x^y, self.numbers)
        #for i in range(1, len(self.numbers)-1):
        #    xor ^= self.numbers[i]
        return(xor)
        
if __name__ == "__main__":
    a = Missing(10**1)
    print(a.missing)

    print(a.find_missing())

6
7


In [31]:
#15.3 permutations

def permutations(A): # returns the list of all possible permutation (each permutation is a list) 
    if len(A) == 1: return(A)
    result = []
    for i in A:
        A_reduced = A.copy()
        A_reduced.remove(i)
        new_permutations_short = permutations(A_reduced)     
        new_permutations_long = [[i]+ p if type(p)==list else [i,p] for p in new_permutations_short]
        result.extend(new_permutations_long)
    
    return(result)

b = ["a","b","c"]
permutations(b)


[['a', 'b', 'c'],
 ['a', 'c', 'b'],
 ['b', 'a', 'c'],
 ['b', 'c', 'a'],
 ['c', 'a', 'b'],
 ['c', 'b', 'a']]

In [26]:
aa = []
a = [[3,4],[5,6],[7,8]]
aa = [i for i in a]
aa 

[[3, 4], [5, 6], [7, 8]]

In [66]:
a = np.arange(10)
mask = np.ones(len(a), dtype=bool)
i = np.floor(np.random.uniform(10))
i

7.0

In [87]:
import functools 

def mycmp(a, b): 
    print("comparing ", a, " and ", b) 
    if a > b: 
        return 1
    elif a < b:
        return(-1)
    else: 
        return(0)
    
print(sorted([1, 2, 4, 2])

SyntaxError: unexpected EOF while parsing (<ipython-input-87-20d82b8f7e17>, line 12)

In [99]:
import functools 

def mycmp(a, b): 
    print("comparing ", a, " and ", b) 
    if a > b: 
        return(-1)
    elif a < b:
        return(1)
    else: 
        return(0)
    
print(sorted([1, 7, 4]))
print(sorted([1, 7, 4], key=functools.cmp_to_key(mycmp))) 

[1, 4, 7]
comparing  7  and  1
comparing  4  and  7
comparing  4  and  1
comparing  4  and  7
[7, 4, 1]


In [100]:
class Foo:
    def __call__(self):
        print('called')

foo_instance = Foo()
foo_instance() #this is calling the __call__ method
print(callable(foo_instance)) 


called
True


In [65]:
#from collections import defaultdic
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 1)]
d = defaultdict(list)
for k, v in s:
    d[k].append(v)
    
sorted(d.items())
d.keys()

dict_keys(['yellow', 'blue', 'red'])

In [ ]:
#import string
def crs(n):    
    return functools.reduce(
        lambda x,y: x + str(y), range(n), '')
#string.hexdigits.index('f')
#a.find(b' ',0)
a = crs(10)
a[3::2]

In [ ]:
graph = {}
graph[1] = [1,2,3]
graph[11] = [11,22,33]
graph[1].pop()
graph[1].pop()
graph[1].pop()

print(graph)

if graph[1]:
    print(True)
else:
    print(False)

1 in graph.keys()

In [107]:
Cat = namedtuple("CAT", "name, color, age")
a = Cat("Cat1", "black", 12)
b = Cat("Cat2", "white", 1)
print(a,b)

CAT(name='Cat1', color='black', age=12) CAT(name='Cat2', color='white', age=1)


In [2]:
a = [1,2,3,4]
for i in range(4):
    print(f'a[~{i}] {a[~i]}; a[{i}] {a[i]}')

ord('c')

a[~0] 4; a[0] 1
a[~1] 3; a[1] 2
a[~2] 2; a[2] 3
a[~3] 1; a[3] 4


99

In [115]:
# Nick's inverview problem
class rectangle:
    
    def __init__(self,  col=7, row=7): 
        self.col = col
        self.row = row
        self.r = np.zeros((col, row))
        self.cluster_id = np.zeros((col, row)) # cluster_id = 0 for zeros or unexplored cells
        self.max_cluster_id = 0 

    def generate(self, p = 0.25): # p is probability of 1
        for i in range(self.col):
            for j in range(self.row):
                self.r[i,j] = rnd.binomial(n = 1, p = p)

    
    def mark_nearby(self, i, j):  
        for ii in range(-1, 2):
            for jj in range(-1,2):
                if i+ii in range (self.row) and j+jj in range(self.col):
                    if self.r[i+ii,j+jj] == 1 and self.cluster_id[i+ii, j+jj] == 0:
                        self.cluster_id[i+ii,j+jj] = self.max_cluster_id
                        self.mark_nearby(i+ii,j+jj)
        
    def count_islands(self):
        for i in range(self.row):
            for j in range(self.col):
                if self.r[i,j] == 1 and self.cluster_id[i, j]  == 0:
                    self.max_cluster_id += 1
                    self.mark_nearby(i,j)

if __name__ == '__main__':
    r = rectangle(17,17)
    r.generate(p = 0.35)
    r.count_islands()
    print(f'we found {r.max_cluster_id} clusters')
    print(f'the matrix we generated \n{r.r} \n') 
    print(f'cluster numbers assigned \n{r.cluster_id}')
    

we found 14 clusters
the matrix we generated 
[[1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1.]] 

cluster numbers assigned 
[[ 1.  